const articles = [
    {
        name: 'first-post',
        title: 'First Post on My New Blog',
        content: [
            `

            First Post Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pulvinar neque ac imperdiet cursus. Duis magna tortor, faucibus ut magna id, ultricies placerat neque. Vivamus et pretium odio, eget porta orci. Vestibulum lacinia condimentum leo, vel pellentesque libero sodales a. Nunc et eros sit amet arcu congue pharetra. Morbi vitae ipsum vitae sem fermentum consectetur eget eu arcu. Sed id quam mauris. Ut urna lacus, fermentum a sagittis quis, fermentum in velit. Mauris fringilla pharetra gravida. Vivamus tortor erat, suscipit consectetur venenatis at, pretium nec odio. Nullam fringilla sem in eros hendrerit lacinia. Aenean imperdiet consectetur augue in bibendum. Cras ornare facilisis risus vel efficitur. Ut elit risus, facilisis quis suscipit ac, rutrum nec enim. Nullam sit amet diam rutrum ante vestibulum malesuada. Vivamus varius orci sed tristique consequat.`,
            
            `Donec gravida nulla at nisi sodales tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam a nisi at arcu vehicula malesuada. Sed varius interdum velit, at ultrices sem sodales eu. Sed suscipit suscipit ligula vitae ullamcorper. Donec at ligula ac orci cursus accumsan eget vel ante. Donec tristique a est et semper. Maecenas tortor tortor, consequat sed condimentum ac, auctor non nulla. Quisque elementum finibus turpis, et iaculis tortor congue fringilla.`,
            
            `Proin vehicula non erat at fringilla. Maecenas vestibulum dui sit amet lectus mollis finibus. Nam hendrerit magna gravida fermentum egestas. In hendrerit ut mi vitae fringilla. Vivamus mollis congue leo ac pulvinar. Nullam vitae metus in enim porttitor bibendum. Nullam ut vestibulum arcu. Integer maximus nisi quis justo gravida, at maximus tortor ornare. Proin lorem est, consequat nec lectus id, tristique eleifend dui. Duis viverra enim a vehicula sollicitudin. Aliquam elementum lectus dapibus convallis lobortis. Vivamus ipsum arcu, elementum ut consequat nec, malesuada et dolor. Vivamus pretium odio quam, sit amet sagittis augue efficitur ut. Duis et ultrices urna, id ultrices tellus. Ut efficitur ex metus, sit amet tincidunt diam convallis eu.`,
            
            `Proin dictum sagittis commodo. Integer molestie risus vel porttitor luctus. Sed maximus quam at dignissim iaculis. Nulla facilisi. Aliquam sed purus in tortor mattis rutrum sed in sapien. Pellentesque libero nisl, blandit vitae rhoncus at, porta sed elit. Nam ornare leo non elit congue, et ullamcorper risus ultrices. Donec mattis cursus posuere. Sed luctus dictum metus, vel faucibus diam elementum eget. Maecenas justo nulla, pretium nec molestie eget, porttitor vel enim. Morbi porta ligula arcu, vitae ultrices risus ultricies et. Donec a quam sed quam iaculis feugiat. Morbi vulputate venenatis nibh quis congue. Ut ullamcorper magna vitae metus congue tincidunt. Aliquam mi ante, gravida id finibus vel, lobortis vitae leo.`,
            
            `Phasellus nec cursus dui. Nam quam justo, varius vitae aliquet et, ultricies sit amet massa. Nam euismod a ex vitae semper. Sed et sem pulvinar, scelerisque felis non, iaculis turpis. Sed mattis dolor et urna elementum, in auctor turpis bibendum. Praesent volutpat vel enim at rutrum. Integer facilisis interdum odio eget fermentum. Cras porta justo et volutpat faucibus. Sed vel finibus nibh. Aenean a dignissim sem. Cras elementum tempus orci, vel malesuada justo rutrum et. Nulla ut lectus vel turpis scelerisque sodales. Suspendisse ac nisi neque. Mauris ultricies tincidunt rutrum. `,
        ]
    },    {
        name: 'second-post',
        title: 'Second Post!',
        content: [
            `

            Second Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pulvinar neque ac imperdiet cursus. Duis magna tortor, faucibus ut magna id, ultricies placerat neque. Vivamus et pretium odio, eget porta orci. Vestibulum lacinia condimentum leo, vel pellentesque libero sodales a. Nunc et eros sit amet arcu congue pharetra. Morbi vitae ipsum vitae sem fermentum consectetur eget eu arcu. Sed id quam mauris. 
            Ut urna lacus, fermentum a sagittis quis, fermentum in velit. Mauris fringilla pharetra gravida. Vivamus tortor erat, suscipit consectetur venenatis at, pretium nec odio. Nullam fringilla sem in eros hendrerit lacinia. Aenean imperdiet consectetur augue in bibendum. Cras ornare facilisis risus vel efficitur. Ut elit risus, facilisis quis suscipit ac, rutrum nec enim. Nullam sit amet diam rutrum ante vestibulum malesuada. Vivamus varius orci sed tristique consequat.`,
          
            `Donec gravida nulla at nisi sodales tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam a nisi at arcu vehicula malesuada. Sed varius interdum velit, at ultrices sem sodales eu. Sed suscipit suscipit ligula vitae ullamcorper. Donec at ligula ac orci cursus accumsan eget vel ante. Donec tristique a est et semper. Maecenas tortor tortor, consequat sed condimentum ac, auctor non nulla. Quisque elementum finibus turpis, et iaculis tortor congue fringilla.`,
            
            `Proin vehicula non erat at fringilla. Maecenas vestibulum dui sit amet lectus mollis finibus. Nam hendrerit magna gravida fermentum egestas. In hendrerit ut mi vitae fringilla. Vivamus mollis congue leo ac pulvinar. Nullam vitae metus in enim porttitor bibendum. Nullam ut vestibulum arcu. Integer maximus nisi quis justo gravida, at maximus tortor ornare. Proin lorem est, consequat nec lectus id, tristique eleifend dui. Duis viverra enim a vehicula sollicitudin. Aliquam elementum lectus dapibus convallis lobortis. Vivamus ipsum arcu, elementum ut consequat nec, malesuada et dolor. Vivamus pretium odio quam, sit amet sagittis augue efficitur ut. Duis et ultrices urna, id ultrices tellus. Ut efficitur ex metus, sit amet tincidunt diam convallis eu.`,
            
            `Proin dictum sagittis commodo. Integer molestie risus vel porttitor luctus. Sed maximus quam at dignissim iaculis. Nulla facilisi. Aliquam sed purus in tortor mattis rutrum sed in sapien. Pellentesque libero nisl, blandit vitae rhoncus at, porta sed elit. Nam ornare leo non elit congue, et ullamcorper risus ultrices. Donec mattis cursus posuere. Sed luctus dictum metus, vel faucibus diam elementum eget. Maecenas justo nulla, pretium nec molestie eget, porttitor vel enim. Morbi porta ligula arcu, vitae ultrices risus ultricies et. Donec a quam sed quam iaculis feugiat. Morbi vulputate venenatis nibh quis congue. Ut ullamcorper magna vitae metus congue tincidunt. Aliquam mi ante, gravida id finibus vel, lobortis vitae leo.`,
            
            `Phasellus nec cursus dui. Nam quam justo, varius vitae aliquet et, ultricies sit amet massa. Nam euismod a ex vitae semper. Sed et sem pulvinar, scelerisque felis non, iaculis turpis. Sed mattis dolor et urna elementum, in auctor turpis bibendum. Praesent volutpat vel enim at rutrum. Integer facilisis interdum odio eget fermentum. Cras porta justo et volutpat faucibus. Sed vel finibus nibh. Aenean a dignissim sem. Cras elementum tempus orci, vel malesuada justo rutrum et. Nulla ut lectus vel turpis scelerisque sodales. Suspendisse ac nisi neque. Mauris ultricies tincidunt rutrum. `,
        ]
    },     {
        name: 'third-post',
        title: 'My third post!',
        content: [
            `

            Third Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pulvinar neque ac imperdiet cursus. Duis magna tortor, faucibus ut magna id, ultricies placerat neque. Vivamus et pretium odio, eget porta orci. Vestibulum lacinia condimentum leo, vel pellentesque libero sodales a. Nunc et eros sit amet arcu congue pharetra. Morbi vitae ipsum vitae sem fermentum consectetur eget eu arcu. Sed id quam mauris. Ut urna lacus, fermentum a sagittis quis, fermentum in velit. Mauris fringilla pharetra gravida. Vivamus tortor erat, suscipit consectetur venenatis at, pretium nec odio. Nullam fringilla sem in eros hendrerit lacinia. Aenean imperdiet consectetur augue in bibendum. Cras ornare facilisis risus vel efficitur. Ut elit risus, facilisis quis suscipit ac, rutrum nec enim. Nullam sit amet diam rutrum ante vestibulum malesuada. Vivamus varius orci sed tristique consequat.`,
            
            `Donec gravida nulla at nisi sodales tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam a nisi at arcu vehicula malesuada. Sed varius interdum velit, at ultrices sem sodales eu. Sed suscipit suscipit ligula vitae ullamcorper. Donec at ligula ac orci cursus accumsan eget vel ante. Donec tristique a est et semper. Maecenas tortor tortor, consequat sed condimentum ac, auctor non nulla. Quisque elementum finibus turpis, et iaculis tortor congue fringilla.`,
            
            `Proin vehicula non erat at fringilla. Maecenas vestibulum dui sit amet lectus mollis finibus. Nam hendrerit magna gravida fermentum egestas. In hendrerit ut mi vitae fringilla. Vivamus mollis congue leo ac pulvinar. Nullam vitae metus in enim porttitor bibendum. Nullam ut vestibulum arcu. Integer maximus nisi quis justo gravida, at maximus tortor ornare. Proin lorem est, consequat nec lectus id, tristique eleifend dui. Duis viverra enim a vehicula sollicitudin. Aliquam elementum lectus dapibus convallis lobortis. Vivamus ipsum arcu, elementum ut consequat nec, malesuada et dolor. Vivamus pretium odio quam, sit amet sagittis augue efficitur ut. Duis et ultrices urna, id ultrices tellus. Ut efficitur ex metus, sit amet tincidunt diam convallis eu.`,
            
            `Proin dictum sagittis commodo. Integer molestie risus vel porttitor luctus. Sed maximus quam at dignissim iaculis. Nulla facilisi. Aliquam sed purus in tortor mattis rutrum sed in sapien. Pellentesque libero nisl, blandit vitae rhoncus at, porta sed elit. Nam ornare leo non elit congue, et ullamcorper risus ultrices. Donec mattis cursus posuere. Sed luctus dictum metus, vel faucibus diam elementum eget. Maecenas justo nulla, pretium nec molestie eget, porttitor vel enim. Morbi porta ligula arcu, vitae ultrices risus ultricies et. Donec a quam sed quam iaculis feugiat. Morbi vulputate venenatis nibh quis congue. Ut ullamcorper magna vitae metus congue tincidunt. Aliquam mi ante, gravida id finibus vel, lobortis vitae leo.`,
            
            `Phasellus nec cursus dui. Nam quam justo, varius vitae aliquet et, ultricies sit amet massa. Nam euismod a ex vitae semper. Sed et sem pulvinar, scelerisque felis non, iaculis turpis. Sed mattis dolor et urna elementum, in auctor turpis bibendum. Praesent volutpat vel enim at rutrum. Integer facilisis interdum odio eget fermentum. Cras porta justo et volutpat faucibus. Sed vel finibus nibh. Aenean a dignissim sem. Cras elementum tempus orci, vel malesuada justo rutrum et. Nulla ut lectus vel turpis scelerisque sodales. Suspendisse ac nisi neque. Mauris ultricies tincidunt rutrum. `,
        ]
    },  
];

export default articles;